[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://wealthwise-backend-es1p.onrender.com/api"
  REACT_APP_SOCKET_URL = "https://wealthwise-backend-es1p.onrender.com"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888
  autoLaunch = true