services:
  - type: web
    name: wealthwise-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run deploy
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://wealthwise-frontend.vercel.app
    disk:
      name: sqlite-storage
      mountPath: /opt/render/project/src/backend
      sizeGB: 1