name: Deploy WealthWise

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    name: Test Backend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
    
    - name: Check backend syntax
      run: |
        cd backend
        node -c server.js
    
    - name: Test backend health
      run: |
        cd backend
        npm start &
        sleep 5
        curl -f http://localhost:5001/health || exit 1
        pkill -f "node server.js"

  test-frontend:
    runs-on: ubuntu-latest
    name: Test Frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build frontend
      run: |
        cd frontend
        CI=false npm run build
      env:
        REACT_APP_API_URL: https://wealthwise-backend.onrender.com/api
        REACT_APP_SOCKET_URL: https://wealthwise-backend.onrender.com

  deploy-notification:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: github.ref == 'refs/heads/main'
    name: Deployment Notification
    
    steps:
    - name: Notify deployment start
      run: |
        echo "🚀 Deployment started for commit ${{ github.sha }}"
        echo "Backend will auto-deploy to Render"
        echo "Frontend will auto-deploy to Vercel"
    
    - name: Create deployment status
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: context.payload.deployment?.id || 0,
            state: 'in_progress',
            description: 'Deploying to Render and Vercel'
          });